# -*- coding: utf-8 -*-
"""Numpy_Class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsHazj5MaTgXqiR1Oq5TrjHum-JmtsYx
"""

import numpy as np

y=np.array([1,2,3])

y/2

x=[1,2,3,"data science"]

type(x[0]),type(x[1]),type(x[2]),type(x[3])

for i in range(1,10):
  print(np.random.randint(0,10))

np.random.randint(0,10,(5,5))

data=np.random.randint(0,100,(5,5))

data[0:3,4:5]

data[-4:-2,-3:-2]

data[0,:]

data[:,0]

data.shape

data.T

x=2

data**2

x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

x

y

np.add(x,2)

np.multiply(x,2)

np.divide(x,2)

np.floor_divide(x,2)

np.exp(x)

np.pow(x,2)

np.random.randn(1300,1300).std()

np.eye(5)

np.zeros(5)

np.ones(5)

np.ones((3,5))

data=np.random.randint(0,10,(5,5))

print(data.sum())
print(data.min())
print(data.max())

data.argmax()

data=np.random.randint(0,10,(3,3))

data.sum(axis=1)

data.sum(axis=0)

data

data

data.max(axis=0)